# Site settings
title: Technomancy
email: elias.bagley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Advanced topics in iOS and Android development
baseurl: ""
url: "http://eliasbagley.github.io" # the base hostname & protocol for your site
twitter_username: eliasbagley
github_username:  eliasbagley
#linkedin_username: elias-bagley

# Build settings
markdown: redcarpet
