# Site settings
title: Elias Bagley's Blog
email: elias.bagley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    A blog for all things that interest me
baseurl: ""
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: eliasbagley
github_username:  eliasbagley

# Build settings
markdown: kramdown
